# Site settings
name: PeerClass
title: PeerClass Blog
description: "A blog about the development process of PeerClass."
url: "http://www.github.com/alxhotel/peerclass"
author:
  name: "Alex"
  email: "alxmorais8@msn.com"

# Build settings
baseurl: /peerclass-blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: :title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
